
[x-axis]
fontsize = 18
where = top


[spacer]
height = 0.2


[GM_STR hic heatmap]
file = /home/x-wding2/Projects/ASC/ASC_loop.Q.cool/GM_STR.Q.cool
title = GM_STR
# cmap: RdYlBu_r, afmhot_r, coolwarm, RdBu, RdYlBu, RdYlGn
colormap = ['wheat', 'white', '#377EB8'] 
# colormap = ['white', 'orange', 'red']
height = 7
transform = no
show_masked_bins = false
rasterize = false
depth = 200000
min_value = 0
max_value = 0.016

# hic_matrix or hic_matrix_square
file_type = hic_matrix


[ links]
file = /home/x-wding2/Projects/ASC/ASC_loop.bedpe/GM_STR.loop.bedpe

height = 0.5
overlay_previous = share-y
# links_type: arcs (default) or triangles, loops or squares
links_type = loops

color = Greens_r
line_width = 0.5
line_style = solid
min_value = 0
max_value = 1
use_middle = true

file_type = links


[GM_exSTR hic heatmap]
file = /home/x-wding2/Projects/ASC/ASC_loop.Q.cool/GM_exSTR.Q.cool
title = GM_exSTR
# cmap: RdYlBu_r, afmhot_r, coolwarm, RdBu, RdYlBu, RdYlGn
colormap = ['wheat', 'white', '#4DAF4A'] 
# colormap = ['white', 'orange', 'red']
height = 7
transform = no
show_masked_bins = false
rasterize = false
depth = 200000
min_value = 0
max_value = 0.016

# hic_matrix or hic_matrix_square
file_type = hic_matrix


[ links]
file = /home/x-wding2/Projects/ASC/ASC_loop.bedpe/GM_exSTR.loop.bedpe

height = 0.5
overlay_previous = share-y
# links_type: arcs (default) or triangles, loops or squares
links_type = loops

color = Greens_r
line_width = 0.5
line_style = solid
min_value = 0
max_value = 1
use_middle = true

file_type = links


[WM hic heatmap]
file = /home/x-wding2/Projects/ASC/ASC_loop.Q.cool/WM.Q.cool
title = WM
# cmap: RdYlBu_r, afmhot_r, coolwarm, RdBu, RdYlBu, RdYlGn
colormap = ['wheat', 'white', '#E41A1C'] 
# colormap = ['white', 'orange', 'red']
height = 7
transform = no
show_masked_bins = false
rasterize = false
depth = 200000
min_value = 0
max_value = 0.016

# hic_matrix or hic_matrix_square
file_type = hic_matrix


[ links]
file = /home/x-wding2/Projects/ASC/ASC_loop.bedpe/WM.loop.bedpe

height = 0.5
overlay_previous = share-y
# links_type: arcs (default) or triangles, loops or squares
links_type = loops

color = Greens_r
line_width = 0.5
line_style = solid
min_value = 0
max_value = 1
use_middle = true

file_type = links


[spacer]
height = 0.1


[bigwig-CGN]
file = /home/x-wding2/Projects/ASC/ASC_methylation/bigwig/GM_STR.CGN-both.frac.bw
title = mCG
height = 2
color = #377EB8
# type: line, points, fill. Default is fill

min_value = 0
max_value=1
number_of_bins = 1000
nans_to_zeros = true
summary_method = mean
show_data_range = true
grid = true
file_type = bigwig


[bigwig-CGN]
file = /home/x-wding2/Projects/ASC/ASC_methylation/bigwig/GM_exSTR.CGN-both.frac.bw
title = mCG
height = 2
color = #4DAF4A
# type: line, points, fill. Default is fill

min_value = 0
max_value=1
number_of_bins = 1000
nans_to_zeros = true
summary_method = mean
show_data_range = true
grid = true
file_type = bigwig


[bigwig-CGN]
file = /home/x-wding2/Projects/ASC/ASC_methylation/bigwig/WM.CGN-both.frac.bw
title = mCG
height = 2
color = #E41A1C
# type: line, points, fill. Default is fill

min_value = 0
max_value=1
number_of_bins = 1000
nans_to_zeros = true
summary_method = mean
show_data_range = true
grid = true
file_type = bigwig


[spacer]
height = 0.1


[bigwig-GM_STR-ATAC]
file = /home/x-wding2/Projects/ASC/ATAC.bigwig/GM_STR.bw
title = ATAC
height = 2
color = #377EB8
# type: line, points, fill. Default is fill

min_value = 0
max_value=2.5
number_of_bins = 1000
nans_to_zeros = true
summary_method = mean
show_data_range = true
grid = true
file_type = bigwig


[bigwig-GM_exSTR-ATAC]
file = /home/x-wding2/Projects/ASC/ATAC.bigwig/GM_exSTR.bw
title = ATAC
height = 2
color = #4DAF4A
# type: line, points, fill. Default is fill

min_value = 0
max_value=2.5
number_of_bins = 1000
nans_to_zeros = true
summary_method = mean
show_data_range = true
grid = true
file_type = bigwig


[bigwig-WM-ATAC]
file = /home/x-wding2/Projects/ASC/ATAC.bigwig/WM.bw
title = ATAC
height = 2
color = #E41A1C
# type: line, points, fill. Default is fill

min_value = 0
max_value=2.5
number_of_bins = 1000
nans_to_zeros = true
summary_method = mean
show_data_range = true
grid = true
file_type = bigwig


[spacer]
height = 0.1


[tads Enhancer]
file = /home/x-wding2/Projects/ASC/ABC.links/GM_STR.bed
title = Enhancer
# file_type: domains (triangles) or bed (squares)
# display: stacked (default) or collapsed, triangles, interleaved, squares, deletions or inversions
display = collapsed

labels = false
file_type = bed
border_color = none
color = jet
min_value=0
max_value=3
height = 0.2
line_width = 2
show_data_range = false


[title = E-P links links]
file = /home/x-wding2/Projects/ASC/ABC.links/GM_STR.bedpe
title = E-P links
height = 1.5
overlay_previous = no
# links_type: arcs (default) or triangles, loops or squares
links_type = arcs
orientation = inverted
color = turbo
line_width = 1
line_style = solid
min_value = 0.02
max_value = 0.05
use_middle = true
compact_arcs_level = 1
file_type = links


[tads Enhancer]
file = /home/x-wding2/Projects/ASC/ABC.links/GM_exSTR.bed
title = Enhancer
# file_type: domains (triangles) or bed (squares)
# display: stacked (default) or collapsed, triangles, interleaved, squares, deletions or inversions
display = collapsed

labels = false
file_type = bed
border_color = none
color = jet
min_value=0
max_value=3
height = 0.2
line_width = 2
show_data_range = false


[title = E-P links links]
file = /home/x-wding2/Projects/ASC/ABC.links/GM_exSTR.bedpe
title = E-P links
height = 1.5
overlay_previous = no
# links_type: arcs (default) or triangles, loops or squares
links_type = arcs
orientation = inverted
color = turbo
line_width = 1
line_style = solid
min_value = 0.02
max_value = 0.05
use_middle = true
compact_arcs_level = 1
file_type = links


[tads Enhancer]
file = /home/x-wding2/Projects/ASC/ABC.links/WM.bed
title = Enhancer
# file_type: domains (triangles) or bed (squares)
# display: stacked (default) or collapsed, triangles, interleaved, squares, deletions or inversions
display = collapsed

labels = false
file_type = bed
border_color = none
color = jet
min_value=0
max_value=3
height = 0.2
line_width = 2
show_data_range = false


[title = E-P links links]
file = /home/x-wding2/Projects/ASC/ABC.links/WM.bedpe
title = E-P links
height = 1.5
overlay_previous = no
# links_type: arcs (default) or triangles, loops or squares
links_type = arcs
orientation = inverted
color = turbo
line_width = 1
line_style = solid
min_value = 0.02
max_value = 0.05
use_middle = true
compact_arcs_level = 1
file_type = links


[spacer]
height = 0.1


file = /anvil/projects/x-mcb130189/Wubin/ASC/figures/DRD1.highlight.bed
type = vhighlight
line_width = 0.5
border_color = black
color = yellow
alpha = 0.3
zorder = -100


[spacer]
height = 0.1


[gencode v43]
file = /home/x-wding2/Ref/hg38/annotations/gencode.v43.annotation.gtf
# title = GTF
height = 5
prefered_name = gene_name
merge_transcripts = true
merge_overlapping_exons = true
color = blue
line_width = 0.5
# display: ['collapsed', 'interleaved', 'triangles', 'squares', 'deletions', 'inversions']
display = stacked
style = UCSC
labels = true
fontsize = 14
gene_rows = 5
labels_in_margin = true
fontstyle = italic
file_type = gtf

# chr5,175440035,175444182,chr5:175400000-175500000
# /home/x-wding2/Software/conda/m3c/bin/pyGenomeTracks --tracks /anvil/projects/x-mcb130189/Wubin/ASC/figures/Marker.DRD1.ini --region chr5:175400000-175500000 --trackLabelFraction 0.05 --trackLabelHAlign left --plotWidth 28 --dpi 300 --fontSize 18 -o /anvil/projects/x-mcb130189/Wubin/ASC/figures/Marker.DRD1.pdf
